export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const ADD_TO_FAVORITES  = "ADD_TO_FAVORITES"
export const REMOVE_FROM_FAVORITES  = "REMOVE_FROM_FAVORITES"
export const INCREMENT_COUNT  = "INCREMENT_COUNT"
